package nutrisoy;

import nutrisoy.command.Command;
import nutrisoy.exception.DukeException;
import nutrisoy.parser.Parser;
import nutrisoy.storage.Storage;
import nutrisoy.task.TaskList;
import nutrisoy.ui.GuiResponse;
import nutrisoy.ui.Ui;

/**
 * Coordinates the NutriSoy application's user interface, storage, and tasks.
 */
public class Duke {
    /** Default file shared by the console and graphical versions of NutriSoy. */
    public static final String DEFAULT_STORAGE_PATH = "./data/nutrisoy.txt";

    private final Storage storage;
    private TaskList tasks;
    private final Ui ui;
    private String startupWarning = "";
    private boolean unsavedChanges;

    /**
     * Creates the application and loads tasks from the specified storage file.
     *
     * @param filePath path to the file used to persist tasks
     */
    public Duke(String filePath) {
        assert filePath != null && !filePath.isBlank() : "Storage file path must be valid";
        ui = new Ui();
        storage = new Storage(filePath);
        try {
            tasks = new TaskList(storage.loadTasks());
            startupWarning = storage.getLoadWarning();
        } catch (DukeException e) {
            startupWarning = e.getMessage();
            tasks = new TaskList();
        }
    }

    /**
     * Runs the command-processing loop until the user exits the application.
     */
    public void run() {
        ui.showWelcome();
        if (!startupWarning.isEmpty()) {
            ui.showLoadingError(startupWarning);
        }
        boolean isExit = false;
        while (!isExit) {
            String fullCommand = ui.readCommand();
            if (fullCommand == null) {
                if (unsavedChanges) {
                    ui.showError("Input closed with unsaved changes. Check the earlier storage error.");
                }
                break;
            }
            ui.showLine();
            GuiResponse response = getGuiResponse(fullCommand);
            ui.showMessage(response.getMessage());
            isExit = response.isExit();
            ui.showLine();
        }
    }

    /**
     * Returns startup diagnostics for display by either user interface.
     *
     * @return warning and recovery advice, or an empty string after a complete load
     */
    public String getStartupWarning() {
        return startupWarning;
    }

    /**
     * Indicates whether closing the window would discard unsaved session changes.
     *
     * @return true if a previous save failed
     */
    public boolean hasUnsavedChanges() {
        return unsavedChanges;
    }

    /**
     * Processes a user command and returns the resulting message for the GUI.
     *
     * @param input command entered by the user
     * @return response generated by the command or an error message
     */
    public String getResponse(String input) {
        return getGuiResponse(input).getMessage();
    }

    /**
     * Processes a user command and includes whether it produced an error so that the GUI can style it clearly.
     *
     * @param input command entered by the user
     * @return response text and its error status
     */
    public GuiResponse getGuiResponse(String input) {
        ui.startCapturingOutput();
        boolean isError = false;
        boolean isExit = false;
        try {
            Command command = Parser.parse(input);
            if (command.changesTasks()) {
                storage.requireSafeSave();
            }
            command.execute(tasks, ui);
            unsavedChanges = unsavedChanges || command.changesTasks();
            if (unsavedChanges) {
                storage.saveTasks(tasks.getTasks());
                unsavedChanges = false;
            }
            isExit = command.isExit();
        } catch (DukeException e) {
            isError = true;
            ui.startCapturingOutput();
            ui.showError(e.getMessage());
            if (unsavedChanges) {
                ui.showMessage(" Changes remain only in this session. Fix storage, then use list to retry saving.");
            }
        }
        return new GuiResponse(ui.stopCapturingOutput(), isError, isExit);
    }

    /**
     * Starts the NutriSoy application.
     *
     * @param args command-line arguments, which are not used
     */
    public static void main(String[] args) {
        new Duke(DEFAULT_STORAGE_PATH).run();
    }
}
