plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '9.5.1'
    id 'checkstyle'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

repositories {
    mavenCentral()
}

dependencies {
    String jUnitVersion = '5.14.4'

    testImplementation "org.junit.jupiter:junit-jupiter-api:${jUnitVersion}"

    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${jUnitVersion}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.14.4'
}

javafx {
    version = '25.0.1'
    modules = ['javafx.controls', 'javafx.fxml']
}

test {
    useJUnitPlatform()

    testLogging {
        events 'passed', 'skipped', 'failed'

        showExceptions = true
        exceptionFormat = 'full'
        showCauses = true
        showStackTraces = true
        showStandardStreams = false
    }
}

application {
    mainClass = 'nutrisoy.ui.Launcher'
}

jar {
    manifest {
        attributes 'Main-Class': 'nutrisoy.ui.Launcher'
    }
    archiveBaseName = 'duke'
    archiveVersion = '0.1.0'
}

shadowJar {
    archiveFileName = 'duke.jar'
}

run {
    standardInput = System.in
}

checkstyle {
    toolVersion = '10.12.4'
    configFile = file("${project.rootDir}/config/checkstyle/checkstyle.xml")
    ignoreFailures = false // Fails the build if any style violation is detected
    showViolations = true
}
